// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7lwjO6tkwhc6jSuj7Tz4_tB5brpXUgE',
    appId: '1:345205985119:web:d9bf7998cc69a32ad1b0ea',
    messagingSenderId: '345205985119',
    projectId: 'app-rental-mobil-3e0ea',
    authDomain: 'app-rental-mobil-3e0ea.firebaseapp.com',
    storageBucket: 'app-rental-mobil-3e0ea.appspot.com',
    measurementId: 'G-V1WDH327VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjBBB1wZz6bG212aFif77iUR-VFIWfA7s',
    appId: '1:345205985119:android:57f5bfd726c1c9d6d1b0ea',
    messagingSenderId: '345205985119',
    projectId: 'app-rental-mobil-3e0ea',
    storageBucket: 'app-rental-mobil-3e0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1tggYqAnPj7eZd9FH9MrUSu6qknhJyRk',
    appId: '1:345205985119:ios:c86a824af04a12a2d1b0ea',
    messagingSenderId: '345205985119',
    projectId: 'app-rental-mobil-3e0ea',
    storageBucket: 'app-rental-mobil-3e0ea.appspot.com',
    iosBundleId: 'com.example.appRentalMobil',
  );
}
